#!/bin/sh
set -e

INDEX="/usr/share/nginx/html/index.html"

sed -i \
  -e "s|__VITE_DEFAULT_WORKSPACE_URL__|${VITE_DEFAULT_WORKSPACE_URL:-}|g" \
  -e "s|__VITE_API_BASE_URL__|${VITE_API_BASE_URL:-}|g" \
  -e "s|__VITE_X_API_KEY__|${VITE_X_API_KEY:-}|g" \
  -e "s|__VITE_RECORDINGS_NAMESPACE__|${VITE_RECORDINGS_NAMESPACE:-}|g" \
  -e "s|__VITE_RECORDINGS_COLLECTION__|${VITE_RECORDINGS_COLLECTION:-}|g" \
  -e "s|__VITE_TODOS_STORE_NAMESPACE__|${VITE_TODOS_STORE_NAMESPACE:-}|g" \
  -e "s|__VITE_TODOS_STORE_NAME__|${VITE_TODOS_STORE_NAME:-}|g" \
  -e "s|__VITE_TODO_AGENT_NAMESPACE__|${VITE_TODO_AGENT_NAMESPACE:-}|g" \
  -e "s|__VITE_TODO_AGENT_NAME__|${VITE_TODO_AGENT_NAME:-}|g" \
  -e "s|__VITE_APPLICATION_MANIFEST__|${VITE_APPLICATION_MANIFEST:-}|g" \
  "$INDEX"

exec nginx -g "daemon off;"
